/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChromeExtensionRouteImport } from './routes/chrome-extension'
import { Route as ChromeRouteImport } from './routes/chrome'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SignupVerifyEmailRouteImport } from './routes/signup/verify-email'
import { Route as SignupCompleteRouteImport } from './routes/signup/complete'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as IngestSplatRouteImport } from './routes/ingest/$'
import { Route as AvatarsSplatRouteImport } from './routes/avatars/$'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username/index'
import { Route as UUsernameFeedDotxmlRouteImport } from './routes/u/$username/feed[.]xml'
import { Route as UUsernameFeedDotatomRouteImport } from './routes/u/$username/feed[.]atom'
import { Route as ApiExtensionImportRouteImport } from './routes/api/extension/import'
import { Route as ApiExtensionBookmarkRouteImport } from './routes/api/extension/bookmark'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiExtensionBookmarkCheckRouteImport } from './routes/api/extension/bookmark.check'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeExtensionRoute = ChromeExtensionRouteImport.update({
  id: '/chrome-extension',
  path: '/chrome-extension',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeRoute = ChromeRouteImport.update({
  id: '/chrome',
  path: '/chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyEmailRoute = SignupVerifyEmailRouteImport.update({
  id: '/signup/verify-email',
  path: '/signup/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCompleteRoute = SignupCompleteRouteImport.update({
  id: '/signup/complete',
  path: '/signup/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarsSplatRoute = AvatarsSplatRouteImport.update({
  id: '/avatars/$',
  path: '/avatars/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFeedDotxmlRoute = UUsernameFeedDotxmlRouteImport.update({
  id: '/u/$username/feed.xml',
  path: '/u/$username/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFeedDotatomRoute = UUsernameFeedDotatomRouteImport.update({
  id: '/u/$username/feed.atom',
  path: '/u/$username/feed.atom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionImportRoute = ApiExtensionImportRouteImport.update({
  id: '/api/extension/import',
  path: '/api/extension/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionBookmarkRoute = ApiExtensionBookmarkRouteImport.update({
  id: '/api/extension/bookmark',
  path: '/api/extension/bookmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionBookmarkCheckRoute =
  ApiExtensionBookmarkCheckRouteImport.update({
    id: '/check',
    path: '/check',
    getParentRoute: () => ApiExtensionBookmarkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/chrome': typeof ChromeRoute
  '/chrome-extension': typeof ChromeExtensionRoute
  '/dashboard': typeof DashboardRoute
  '/extension': typeof ExtensionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/og': typeof ApiOgRoute
  '/avatars/$': typeof AvatarsSplatRoute
  '/ingest/$': typeof IngestSplatRoute
  '/rpc/$': typeof RpcSplatRoute
  '/signup/complete': typeof SignupCompleteRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/signup/': typeof SignupIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/bookmark': typeof ApiExtensionBookmarkRouteWithChildren
  '/api/extension/import': typeof ApiExtensionImportRoute
  '/u/$username/feed.atom': typeof UUsernameFeedDotatomRoute
  '/u/$username/feed.xml': typeof UUsernameFeedDotxmlRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/api/extension/bookmark/check': typeof ApiExtensionBookmarkCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/chrome': typeof ChromeRoute
  '/chrome-extension': typeof ChromeExtensionRoute
  '/dashboard': typeof DashboardRoute
  '/extension': typeof ExtensionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/og': typeof ApiOgRoute
  '/avatars/$': typeof AvatarsSplatRoute
  '/ingest/$': typeof IngestSplatRoute
  '/rpc/$': typeof RpcSplatRoute
  '/signup/complete': typeof SignupCompleteRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/signup': typeof SignupIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/bookmark': typeof ApiExtensionBookmarkRouteWithChildren
  '/api/extension/import': typeof ApiExtensionImportRoute
  '/u/$username/feed.atom': typeof UUsernameFeedDotatomRoute
  '/u/$username/feed.xml': typeof UUsernameFeedDotxmlRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/api/extension/bookmark/check': typeof ApiExtensionBookmarkCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/chrome': typeof ChromeRoute
  '/chrome-extension': typeof ChromeExtensionRoute
  '/dashboard': typeof DashboardRoute
  '/extension': typeof ExtensionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/og': typeof ApiOgRoute
  '/avatars/$': typeof AvatarsSplatRoute
  '/ingest/$': typeof IngestSplatRoute
  '/rpc/$': typeof RpcSplatRoute
  '/signup/complete': typeof SignupCompleteRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/signup/': typeof SignupIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/bookmark': typeof ApiExtensionBookmarkRouteWithChildren
  '/api/extension/import': typeof ApiExtensionImportRoute
  '/u/$username/feed.atom': typeof UUsernameFeedDotatomRoute
  '/u/$username/feed.xml': typeof UUsernameFeedDotxmlRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/api/extension/bookmark/check': typeof ApiExtensionBookmarkCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/chrome'
    | '/chrome-extension'
    | '/dashboard'
    | '/extension'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/$'
    | '/api/avatar'
    | '/api/og'
    | '/avatars/$'
    | '/ingest/$'
    | '/rpc/$'
    | '/signup/complete'
    | '/signup/verify-email'
    | '/signup/'
    | '/api/auth/$'
    | '/api/extension/bookmark'
    | '/api/extension/import'
    | '/u/$username/feed.atom'
    | '/u/$username/feed.xml'
    | '/u/$username/'
    | '/api/extension/bookmark/check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/chrome'
    | '/chrome-extension'
    | '/dashboard'
    | '/extension'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/$'
    | '/api/avatar'
    | '/api/og'
    | '/avatars/$'
    | '/ingest/$'
    | '/rpc/$'
    | '/signup/complete'
    | '/signup/verify-email'
    | '/signup'
    | '/api/auth/$'
    | '/api/extension/bookmark'
    | '/api/extension/import'
    | '/u/$username/feed.atom'
    | '/u/$username/feed.xml'
    | '/u/$username'
    | '/api/extension/bookmark/check'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/chrome'
    | '/chrome-extension'
    | '/dashboard'
    | '/extension'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/$'
    | '/api/avatar'
    | '/api/og'
    | '/avatars/$'
    | '/ingest/$'
    | '/rpc/$'
    | '/signup/complete'
    | '/signup/verify-email'
    | '/signup/'
    | '/api/auth/$'
    | '/api/extension/bookmark'
    | '/api/extension/import'
    | '/u/$username/feed.atom'
    | '/u/$username/feed.xml'
    | '/u/$username/'
    | '/api/extension/bookmark/check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangelogRoute: typeof ChangelogRoute
  ChromeRoute: typeof ChromeRoute
  ChromeExtensionRoute: typeof ChromeExtensionRoute
  DashboardRoute: typeof DashboardRoute
  ExtensionRoute: typeof ExtensionRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiOgRoute: typeof ApiOgRoute
  AvatarsSplatRoute: typeof AvatarsSplatRoute
  IngestSplatRoute: typeof IngestSplatRoute
  RpcSplatRoute: typeof RpcSplatRoute
  SignupCompleteRoute: typeof SignupCompleteRoute
  SignupVerifyEmailRoute: typeof SignupVerifyEmailRoute
  SignupIndexRoute: typeof SignupIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExtensionBookmarkRoute: typeof ApiExtensionBookmarkRouteWithChildren
  ApiExtensionImportRoute: typeof ApiExtensionImportRoute
  UUsernameFeedDotatomRoute: typeof UUsernameFeedDotatomRoute
  UUsernameFeedDotxmlRoute: typeof UUsernameFeedDotxmlRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrome-extension': {
      id: '/chrome-extension'
      path: '/chrome-extension'
      fullPath: '/chrome-extension'
      preLoaderRoute: typeof ChromeExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrome': {
      id: '/chrome'
      path: '/chrome'
      fullPath: '/chrome'
      preLoaderRoute: typeof ChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/verify-email': {
      id: '/signup/verify-email'
      path: '/signup/verify-email'
      fullPath: '/signup/verify-email'
      preLoaderRoute: typeof SignupVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/complete': {
      id: '/signup/complete'
      path: '/signup/complete'
      fullPath: '/signup/complete'
      preLoaderRoute: typeof SignupCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatars/$': {
      id: '/avatars/$'
      path: '/avatars/$'
      fullPath: '/avatars/$'
      preLoaderRoute: typeof AvatarsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/feed.xml': {
      id: '/u/$username/feed.xml'
      path: '/u/$username/feed.xml'
      fullPath: '/u/$username/feed.xml'
      preLoaderRoute: typeof UUsernameFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/feed.atom': {
      id: '/u/$username/feed.atom'
      path: '/u/$username/feed.atom'
      fullPath: '/u/$username/feed.atom'
      preLoaderRoute: typeof UUsernameFeedDotatomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/import': {
      id: '/api/extension/import'
      path: '/api/extension/import'
      fullPath: '/api/extension/import'
      preLoaderRoute: typeof ApiExtensionImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/bookmark': {
      id: '/api/extension/bookmark'
      path: '/api/extension/bookmark'
      fullPath: '/api/extension/bookmark'
      preLoaderRoute: typeof ApiExtensionBookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/bookmark/check': {
      id: '/api/extension/bookmark/check'
      path: '/check'
      fullPath: '/api/extension/bookmark/check'
      preLoaderRoute: typeof ApiExtensionBookmarkCheckRouteImport
      parentRoute: typeof ApiExtensionBookmarkRoute
    }
  }
}

interface ApiExtensionBookmarkRouteChildren {
  ApiExtensionBookmarkCheckRoute: typeof ApiExtensionBookmarkCheckRoute
}

const ApiExtensionBookmarkRouteChildren: ApiExtensionBookmarkRouteChildren = {
  ApiExtensionBookmarkCheckRoute: ApiExtensionBookmarkCheckRoute,
}

const ApiExtensionBookmarkRouteWithChildren =
  ApiExtensionBookmarkRoute._addFileChildren(ApiExtensionBookmarkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangelogRoute: ChangelogRoute,
  ChromeRoute: ChromeRoute,
  ChromeExtensionRoute: ChromeExtensionRoute,
  DashboardRoute: DashboardRoute,
  ExtensionRoute: ExtensionRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiOgRoute: ApiOgRoute,
  AvatarsSplatRoute: AvatarsSplatRoute,
  IngestSplatRoute: IngestSplatRoute,
  RpcSplatRoute: RpcSplatRoute,
  SignupCompleteRoute: SignupCompleteRoute,
  SignupVerifyEmailRoute: SignupVerifyEmailRoute,
  SignupIndexRoute: SignupIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExtensionBookmarkRoute: ApiExtensionBookmarkRouteWithChildren,
  ApiExtensionImportRoute: ApiExtensionImportRoute,
  UUsernameFeedDotatomRoute: UUsernameFeedDotatomRoute,
  UUsernameFeedDotxmlRoute: UUsernameFeedDotxmlRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
